=== Reinhammar/xmlproject/scoretracker.dtd
<!ELEMENT scoretracker (player,scores)>
<!ELEMENT player (iidxid,djname)>
<!ELEMENT iidxid (#PCDATA)>
<!ELEMENT djname (#PCDATA)>
<!ELEMENT scores (song*)>
<!ELEMENT song (title,chart,lamp,exscore,link)>
<!ATTLIST song musicid CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT chart (#PCDATA)>
<!ELEMENT lamp (#PCDATA)>
<!ELEMENT exscore (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== Reinhammar/xmlproject/scoretracker.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE scoretracker SYSTEM "http://xml.csc.kth.se/~dsw/DM2517/project/scoretracker.dtd">
<scoretracker>
	<player>
		<iidxid>10352753</iidxid>
		<djname>SEPHY</djname>
	</player>
	<scores>
		<song musicid="21008">
			<title>Insane Techniques</title>
			<chart>2</chart>
			<lamp>4</lamp>
			<exscore>2009</exscore>
			<link>https://remywiki.com/Insane_Techniques</link>
		</song>
		<song musicid="21085">
			<title>Cleopatrysm</title>
			<chart>0</chart>
			<lamp>7</lamp>
			<exscore>772</exscore>
			<link>https://remywiki.com/Cleopatrysm</link>
		</song>
	</scores>
</scoretracker>
